### ISSUE TITLE
The error does not return if the file name does not end on json, yaml etc.

### ISSUE THREAD

**Issue by podtserkovskiy** [koding/multiconfig#60]
configLoader := multiconfig.NewWithPath("1111")
err := configLoader.Load(c)

**Comment by rjeczalik** [comment]
On a second thought I'm removing the `bug` label.

This is somewhat API issue here - NewWithPath does not return errors so you can't simply fail [here](https://github.com/koding/multiconfig/blob/master/multiconfig.go#L42) if unexpected extension is detected (moreover the ifs could be improved to test for ".toml" instead of "toml" and so on).

Way of fixing this would be adding ErrorLoader and registering it when no valid extension is found, but it would change the behaviour the function currently has. And from the looks I think the silent failure is by design. 🤔

**Comment by cihangir** [comment]
Hi, yes this is not a bug, where we are creating a *default loader* with the given filename with a best effort. If someone needs more granular work, could use [MultiLoader](https://github.com/koding/koding/blob/ba0fa3efcbcb26eb1ce7aa5612dc405db37e32a8/go/src/vendor/github.com/koding/multiconfig/file_test.go#L26-L30) and get the errors.


You can see more real-world usages [here](https://github.com/koding/koding/search?utf8=%E2%9C%93&q=MultiLoader)
